# Generated by lib/tasks/moudamepo.rake
#  rake moudamepo:fetch > db/seeds.rb
#  generated at 2019-01-06 20:40:59 +0900

Category.create(:name => 'NEWS') # moudamepo's id = 10
Category.create(:name => 'VIP') # moudamepo's id = 11
Category.create(:name => '芸能') # moudamepo's id = 12
Category.create(:name => 'スポーツ') # moudamepo's id = 13
Category.create(:name => 'アニ漫') # moudamepo's id = 14
Category.create(:name => 'ゲーム') # moudamepo's id = 15
Category.create(:name => 'AA:SS') # moudamepo's id = 16
Category.create(:name => '生活') # moudamepo's id = 17
Category.create(:name => '翻訳') # moudamepo's id = 18
Category.create(:name => 'その他') # moudamepo's id = 19
# Mapping for moudamepo.com name to autoincrement id.
category_name_binds = {
  'NEWS' => 1,
  'VIP' => 2,
  '芸能' => 3,
  'スポーツ' => 4,
  'アニ漫' => 5,
  'ゲーム' => 6,
  'AA:SS' => 7,
  '生活' => 8,
  '翻訳' => 9,
  'その他' => 10,
}
# Mapping for moudamepo.com id to autoincrement id.
category_id_binds = {
  10 => 1,
  11 => 2,
  12 => 3,
  13 => 4,
  14 => 5,
  15 => 6,
  16 => 7,
  17 => 8,
  18 => 9,
  19 => 10,
}
# Site PAGE: 1/8 ----------------
s = Site.create(:name => %q#雪夜速報(●ﾟДﾟ●)TWINEWS！#, 
  :url => 'http://nadarenews.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://nadarenews.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 89025)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 412986)
s = Site.create(:name => %q#ポッカキット#, 
  :url => 'http://www.po-kaki-to.com', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://www.po-kaki-to.com/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 86444)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 223731)
s = Site.create(:name => %q#キニ速#, 
  :url => 'http://blog.livedoor.jp/kinisoku/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://blog.livedoor.jp/kinisoku/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 74460)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 104497)
s = Site.create(:name => %q#あじあニュースちゃんねる#, 
  :url => 'http://toua2chdqn.livedoor.blog/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://toua2chdqn.livedoor.blog/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 71654)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 305851)
s = Site.create(:name => %q#保守速報#, 
  :url => 'http://hosyusokuhou.jp', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://hosyusokuhou.jp/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 63671)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 137818)
s = Site.create(:name => %q#なんじぇいスタジアム＠なんJまとめ#, 
  :url => 'http://blog.livedoor.jp/nanjstu/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/nanjstu/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 59117)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 44671)
s = Site.create(:name => %q#大艦巨砲主義！#, 
  :url => 'http://military38.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://military38.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 57343)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 100855)
s = Site.create(:name => %q#暇つぶしニュース#, 
  :url => 'http://blog.livedoor.jp/rbkyn844/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://blog.livedoor.jp/rbkyn844/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 45053)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 112918)
s = Site.create(:name => %q#News U.S.#, 
  :url => 'http://news-us.org', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://news-us.org/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 43054)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 129536)
s = Site.create(:name => %q#アニゲー速報#, 
  :url => 'http://www.anige-sokuhouvip.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://www.anige-sokuhouvip.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 39703)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 109521)
s = Site.create(:name => %q#NEWSまとめもりー｜2chまとめブログ#, 
  :url => 'http://www.akb48matomemory.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.akb48matomemory.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 36992)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 119885)
s = Site.create(:name => %q#不思議.net#, 
  :url => 'http://world-fusigi.net/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://world-fusigi.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 36325)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 39570)
s = Site.create(:name => %q#ぴこ速(〃'∇'〃)？#, 
  :url => 'https://pioncoo.net', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'https://pioncoo.net/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 33088)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 140356)
s = Site.create(:name => %q#なんJ PRIDE#, 
  :url => 'http://blog.livedoor.jp/rock1963roll/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/rock1963roll/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 31683)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 33347)
s = Site.create(:name => %q#かぞくちゃんねる#, 
  :url => 'http://kazokuchannel.doorblog.jp/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kazokuchannel.doorblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 27672)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 82988)
s = Site.create(:name => %q#U-1 NEWS#, 
  :url => 'http://japannews01.blog.jp/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://japannews01.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 27045)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 125978)
s = Site.create(:name => %q#【海外の反応】　パンドラの憂鬱#, 
  :url => 'http://kaigainohannoublog.blog55.fc2.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://kaigainohannoublog.blog55.fc2.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 26733)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 63303)
s = Site.create(:name => %q#軍事・ミリタリー速報☆彡#, 
  :url => 'http://blog.livedoor.jp/corez18c24-mili777/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://blog.livedoor.jp/corez18c24-mili777/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 25716)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 53236)
s = Site.create(:name => %q#おーるじゃんる#, 
  :url => 'http://crx7601.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://crx7601.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 20670)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 63113)
s = Site.create(:name => %q#もえるあじあ(･∀･)#, 
  :url => 'http://www.moeruasia.net', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.moeruasia.net/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 19601)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 105085)
s = Site.create(:name => %q#オーバージョイド！　　2chまとめサイト#, 
  :url => 'http://overjoyed.info', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://overjoyed.info/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 19301)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 67706)
s = Site.create(:name => %q#Nニュースα#, 
  :url => 'http://nnews1.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://nnews1.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 18868)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 186471)
s = Site.create(:name => %q#きらりちゃんねる ～修羅場・鬼女・生活2chまとめ～#, 
  :url => 'http://kirari-ch.blog.jp/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kirari-ch.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 18829)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 55302)
s = Site.create(:name => %q#VIPワイドガイド#, 
  :url => 'http://news4wide.livedoor.biz/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://news4wide.livedoor.biz/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 18685)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 74184)
s = Site.create(:name => %q#修羅場ハザード -復讐・DQN返し・衝撃系まとめ-#, 
  :url => 'http://syurabahazard.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://syurabahazard.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 18483)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 56064)
# Site PAGE: 2/8 ----------------
s = Site.create(:name => %q#妹はVIPPER#, 
  :url => 'http://vipsister23.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://vipsister23.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 17824)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 94180)
s = Site.create(:name => %q#あ艦これ ～艦隊これくしょんまとめブログ～#, 
  :url => 'http://akankore.doorblog.jp/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://akankore.doorblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 17718)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 15208)
s = Site.create(:name => %q#衝撃体験！アンビリバボー｜浮気・不倫・修羅場・離婚#, 
  :url => 'http://uwakitaiken.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://uwakitaiken.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 16624)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 57127)
s = Site.create(:name => %q#まじかる☆にゅーす#, 
  :url => 'http://magical-news.blog.jp/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://magical-news.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 15863)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 63406)
s = Site.create(:name => %q#日刊やきう速報＠野球まとめ#, 
  :url => 'http://blog.livedoor.jp/yakiusoku/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/yakiusoku/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 15446)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 18646)
s = Site.create(:name => %q#ジャンプまとめ速報#, 
  :url => 'http://jumpmatome2ch.biz', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://jumpmatome2ch.biz/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 14591)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 26032)
s = Site.create(:name => %q#世界の憂鬱  海外・韓国の反応#, 
  :url => 'http://blog.livedoor.jp/sekaiminzoku/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://blog.livedoor.jp/sekaiminzoku/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 14223)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 60803)
s = Site.create(:name => %q#1000mg#, 
  :url => 'http://1000mg.jp', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://1000mg.jp/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 13537)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 14900)
s = Site.create(:name => %q#女子アナお宝画像速報#, 
  :url => 'http://blog.livedoor.jp/a_load/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://blog.livedoor.jp/a_load/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 13288)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 83188)
s = Site.create(:name => %q#GUNDAM.LOG｜ガンダムまとめブログ#, 
  :url => 'http://gundamlog.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://gundamlog.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 12928)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 19275)
s = Site.create(:name => %q#暇人＼(^o^)／速報#, 
  :url => 'http://himasoku.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://himasoku.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 12855)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 39937)
s = Site.create(:name => %q#乃木坂46まとめ 1/46#, 
  :url => 'http://nogizaka-46bunno1.blog.jp/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://nogizaka-46bunno1.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 12652)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 26482)
s = Site.create(:name => %q#AKB48タイムズ（AKB48まとめ）#, 
  :url => 'http://akb48taimuzu.livedoor.biz/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://akb48taimuzu.livedoor.biz/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 11634)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 17998)
s = Site.create(:name => %q#乃木坂46まとめもらんだむ|乃木坂46・欅坂46まとめ速報#, 
  :url => 'http://nogizaka46matome.2chblog.jp/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://nogizaka46matome.2chblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 11407)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 24903)
s = Site.create(:name => %q# じゃぱそく！#, 
  :url => 'http://jpsoku.blog.jp/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://jpsoku.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 11015)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 31015)
s = Site.create(:name => %q#でっちでち速報#, 
  :url => 'http://dechisoku.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://dechisoku.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 10108)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 18827)
s = Site.create(:name => %q#阪神タイガースちゃんねる#, 
  :url => 'http://hanshintigers1.blog.jp/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://hanshintigers1.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 9966)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 25411)
s = Site.create(:name => %q#カイカイ反応通信#, 
  :url => 'http://blog.livedoor.jp/kaikaihanno/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://blog.livedoor.jp/kaikaihanno/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 9962)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 33564)
s = Site.create(:name => %q#芸能かめはめ波#, 
  :url => 'http://geinoukame.blog.fc2.com/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://geinoukame.blog.fc2.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 9954)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 59056)
s = Site.create(:name => %q#seiyu fan#, 
  :url => 'http://seiyufan.livedoor.biz/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://seiyufan.livedoor.biz/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 9849)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 29143)
s = Site.create(:name => %q#すかっとしていきませんか | sk2ch#, 
  :url => 'http://sk2ch.net', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://sk2ch.net/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 9765)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 19680)
s = Site.create(:name => %q# /)；｀ω´)＜国家総動員報#, 
  :url => 'http://totalwar.doorblog.jp/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://totalwar.doorblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 9757)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 74228)
s = Site.create(:name => %q#エクサワロス | ニュース系2chまとめブログ#, 
  :url => 'http://exawarosu.net/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://exawarosu.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 9755)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 74495)
s = Site.create(:name => %q#正義の見方#, 
  :url => 'http://www.honmotakeshi.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.honmotakeshi.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 9746)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 37675)
s = Site.create(:name => %q#厳選！韓国情報#, 
  :url => 'http://gensen2ch.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://gensen2ch.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 9118)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 33809)
# Site PAGE: 3/8 ----------------
s = Site.create(:name => %q#ワロタニッキ#, 
  :url => 'http://warotanikki.com', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://warotanikki.com/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 8943)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 24925)
s = Site.create(:name => %q#ぶる速-VIP#, 
  :url => 'http://burusoku-vip.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://burusoku-vip.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 8747)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 32531)
s = Site.create(:name => %q#キムチ速報#, 
  :url => 'http://kimsoku.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://kimsoku.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 8746)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 48044)
s = Site.create(:name => %q#なんJ（まとめては）いかんのか？#, 
  :url => 'http://blog.livedoor.jp/livejupiter2/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/livejupiter2/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 8453)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6248)
s = Site.create(:name => %q#チラ速 (*￣ω￣)/ -画像2chまとめブログ-#, 
  :url => 'http://blog.livedoor.jp/nichmatomerunn/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://blog.livedoor.jp/nichmatomerunn/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 8137)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 40554)
s = Site.create(:name => %q#NOGIVIOLA＠乃木坂46まとめ#, 
  :url => 'http://nogiviola.livedoor.biz/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://nogiviola.livedoor.biz/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 7848)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 16705)
s = Site.create(:name => %q#ヒーローNEWS#, 
  :url => 'http://hero-news.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://hero-news.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 7700)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 10449)
s = Site.create(:name => %q#ニコニコVIP2ch#, 
  :url => 'http://blog.livedoor.jp/nicovip2ch/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://blog.livedoor.jp/nicovip2ch/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 7675)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 75493)
s = Site.create(:name => %q#笑　韓　ブログ#, 
  :url => 'http://www.wara2ch.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.wara2ch.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 7672)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 18025)
s = Site.create(:name => %q#素敵な鬼女様#, 
  :url => 'http://sutekinakijo.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://sutekinakijo.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 7638)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 23329)
s = Site.create(:name => %q#fig速#, 
  :url => 'http://figsoku.net', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://figsoku.net/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 7586)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6919)
s = Site.create(:name => %q#NEWS+α#, 
  :url => 'http://newsplusalpha.net/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://newsplusalpha.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 7455)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 22505)
s = Site.create(:name => %q#鬼女はみた -修羅場・恋愛・育児系まとめサイト-#, 
  :url => 'http://kijyomita.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kijyomita.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 7432)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 22469)
s = Site.create(:name => %q#かんむす！-艦隊これくしょんまとめブログ-#, 
  :url => 'http://kanmsu.com', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://kanmsu.com/?feed=rss2')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 7348)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 9415)
s = Site.create(:name => %q#スコールちゃんねる｜２ちゃんまとめブログ#, 
  :url => 'http://squallchannel.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://squallchannel.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 7317)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 17461)
s = Site.create(:name => %q#どんぐりこ - 海外の反応#, 
  :url => 'http://dng65.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://dng65.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 6851)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 28924)
s = Site.create(:name => %q#艦これ速報　艦隊これくしょんまとめ#, 
  :url => 'http://kancolle.doorblog.jp/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://kancolle.doorblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 6824)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 8655)
s = Site.create(:name => %q#海外の万国反応記＠海外の反応#, 
  :url => 'http://www.all-nationz.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://www.all-nationz.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 6817)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 26187)
s = Site.create(:name => %q#おにひめちゃんの監視部屋-鬼女、キチママ、修羅場、生活まとめ-#, 
  :url => 'http://onihimechan.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://onihimechan.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 6678)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 21396)
s = Site.create(:name => %q#まるごと速報#, 
  :url => 'http://maru-soku.com', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://maru-soku.com/?feed=rss2')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 6583)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 23146)
s = Site.create(:name => %q#キチガイママまとめ保管庫#, 
  :url => 'http://www.kitimama-matome.net/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://www.kitimama-matome.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 6481)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 9508)
s = Site.create(:name => %q#ムダスレ無き改革#, 
  :url => 'http://mudasure.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://mudasure.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 6292)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 13938)
s = Site.create(:name => %q#気になった生活スレまとめ#, 
  :url => 'http://kininatta2chmatome.doorblog.jp/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kininatta2chmatome.doorblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 6207)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 12085)
s = Site.create(:name => %q#セロリのきんぴら#, 
  :url => 'http://celery.diary.to/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://celery.diary.to/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 6202)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 9875)
s = Site.create(:name => %q#最強ジャンプ放送局#, 
  :url => 'http://www.saikyo-jump.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://www.saikyo-jump.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 6168)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 14939)
# Site PAGE: 4/8 ----------------
s = Site.create(:name => %q#鬼女まとめ速報 -修羅場・キチママ・生活まとめ-#, 
  :url => 'http://kijyomatome.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kijyomatome.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5943)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 22792)
s = Site.create(:name => %q#アナきゃぷ速報#, 
  :url => 'http://anacap.doorblog.jp/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://anacap.doorblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5909)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 10556)
s = Site.create(:name => %q#まにゅそく 2chまとめニュース速報VIP#, 
  :url => 'http://2ch-matomenews.com', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://2ch-matomenews.com/feed/')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5856)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 40780)
s = Site.create(:name => %q#【2ch】ニュー速クオリティ#, 
  :url => 'http://news4vip.livedoor.biz/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://news4vip.livedoor.biz/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5778)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 19281)
s = Site.create(:name => %q#思考ちゃんねる#, 
  :url => 'http://mindhack2ch.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://mindhack2ch.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5757)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 45402)
s = Site.create(:name => %q#スロ板-RUSH#, 
  :url => 'http://fiveslot777.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://fiveslot777.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5743)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6251)
s = Site.create(:name => %q#修羅場まとめ速報#, 
  :url => 'http://shuraba-matome.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://shuraba-matome.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5586)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 24009)
s = Site.create(:name => %q#­海外反応　キキミミ#, 
  :url => 'http://xxxkikimimixxx.blog.fc2.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://xxxkikimimixxx.blog.fc2.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5550)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 38585)
s = Site.create(:name => %q#政経ワロスまとめニュース♪#, 
  :url => 'http://seikeidouga.blog.jp/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://seikeidouga.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5486)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 47542)
s = Site.create(:name => %q#ニュース30over#, 
  :url => 'http://www.news30over.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.news30over.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5311)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 21158)
s = Site.create(:name => %q#SS 森きのこ！#, 
  :url => 'http://morikinoko.com/', 
  :category_id => category_name_binds['AA:SS'], 
  :feed_url => 'http://morikinoko.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5277)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1595)
s = Site.create(:name => %q#みんなの暇つぶし#, 
  :url => 'http://minnanohimatubushi.2chblog.jp/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://minnanohimatubushi.2chblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5216)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 24831)
s = Site.create(:name => %q#政経ch#, 
  :url => 'http://fxya.blog129.fc2.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://fxya.blog129.fc2.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5111)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 22876)
s = Site.create(:name => %q#【2ch】コピペ情報局#, 
  :url => 'http://news.2chblog.jp/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://news.2chblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 5093)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 22337)
s = Site.create(:name => %q#億ったー#, 
  :url => 'http://www.okutta.net/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.okutta.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4844)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 39063)
s = Site.create(:name => %q#まとめたニュース#, 
  :url => 'http://matometanews.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://matometanews.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4772)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 39456)
s = Site.create(:name => %q#おたほー#, 
  :url => 'http://blog.livedoor.jp/otataho/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://blog.livedoor.jp/otataho/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4744)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 16297)
s = Site.create(:name => %q#気団まとめ-噫無情-｜嫁・浮気・メシマズ#, 
  :url => 'http://kidan-m.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kidan-m.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4540)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 17554)
s = Site.create(:name => %q#パズ速 -パズドラ情報まとめ-#, 
  :url => 'http://pazusoku.blog.fc2.com/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://pazusoku.blog.fc2.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4522)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1167)
s = Site.create(:name => %q#鯉速＠広島東洋カープまとめブログ#, 
  :url => 'http://koisoku.ldblog.jp/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://koisoku.ldblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4477)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1314)
s = Site.create(:name => %q#渡る世間はキチばかり - 鬼女・修羅場・キチママ・義家族まとめ-#, 
  :url => 'http://watarukiti.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://watarukiti.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4419)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 13534)
s = Site.create(:name => %q#基地沢直樹-復讐・修羅場・DQN返し【2chスカッとする話まとめ...#, 
  :url => 'http://kitizawa.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kitizawa.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4339)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 12955)
s = Site.create(:name => %q#ちゃん速#, 
  :url => 'http://chansoku.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://chansoku.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4230)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 11739)
s = Site.create(:name => %q#竜速（りゅうそく）#, 
  :url => 'http://blog.livedoor.jp/bbyakyu/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/bbyakyu/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4229)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 2468)
# Site PAGE: 5/8 ----------------
s = Site.create(:name => %q#子育てちゃんねる#, 
  :url => 'http://kosodatech.blog133.fc2.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://feeds.fc2.com/fc2/xml?host=kosodatech.blog133')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4206)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 7353)
s = Site.create(:name => %q#ガールズVIPまとめ#, 
  :url => 'http://girlsvip-matome.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://girlsvip-matome.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4158)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 13459)
s = Site.create(:name => %q#2ch東方スレ観測所#, 
  :url => 'http://blog.livedoor.jp/coleblog/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://blog.livedoor.jp/coleblog/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4142)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1255)
s = Site.create(:name => %q#鬼女梅#, 
  :url => 'http://kijoume.net/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kijoume.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 4010)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 12058)
s = Site.create(:name => %q#ガハろぐNewsヽ(･ω･)/ｽﾞｺｰ#, 
  :url => 'http://gahalog.2chblog.jp/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://gahalog.2chblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3997)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 14759)
s = Site.create(:name => %q#スロログ#, 
  :url => 'http://slotlog.net/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://slotlog.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3835)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 3875)
s = Site.create(:name => %q#働くモノニュース : 人生VIP職人ブログwww#, 
  :url => 'http://workingnews.blog117.fc2.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://workingnews.blog117.fc2.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3794)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6569)
s = Site.create(:name => %q#それからの出来事() アイマスまとめ#, 
  :url => 'http://sorekarano.blomaga.jp/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://sorekarano.blomaga.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3770)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 2447)
s = Site.create(:name => %q#(*ﾟ∀ﾟ)ゞカガクニュース隊#, 
  :url => 'http://www.scienceplus2ch.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://www.scienceplus2ch.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3752)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 17905)
s = Site.create(:name => %q#欅坂46まとめもり～#, 
  :url => 'http://keyakizaka46matomemory.net/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://keyakizaka46matomemory.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3740)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6411)
s = Site.create(:name => %q#かんこく！　韓国の反応翻訳ブログ#, 
  :url => 'http://kankokunohannou.org/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://kankokunohannou.org/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3544)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 28252)
s = Site.create(:name => %q#V速ニュップ#, 
  :url => 'http://www.vsnp.net/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://www.vsnp.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3517)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 10794)
s = Site.create(:name => %q#虹神速報-にじそく#, 
  :url => 'http://nizigami.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://nizigami.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3403)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6590)
s = Site.create(:name => %q#ニュー速VIPブログ(`･ω･´)#, 
  :url => 'http://blog.livedoor.jp/insidears/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://blog.livedoor.jp/insidears/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3379)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 2995)
s = Site.create(:name => %q#FX2ちゃんねる|投資系2chまとめ#, 
  :url => 'http://www.fx2ch.net', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://www.fx2ch.net/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3368)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 2530)
s = Site.create(:name => %q#海外の反応　お隣速報#, 
  :url => 'http://www.otonarisoku.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://www.otonarisoku.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3326)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 27901)
s = Site.create(:name => %q#（　｀ハ´）中国の反応ブログ#, 
  :url => 'http://asiareaction.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://asiareaction.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3302)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 12676)
s = Site.create(:name => %q#ああ言えばForYou#, 
  :url => 'http://aaieba.livedoor.biz/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://aaieba.livedoor.biz/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3271)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 5867)
s = Site.create(:name => %q#ゆめ痛 -NEWS ALERT-#, 
  :url => 'http://blog.livedoor.jp/yu_ps13/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://blog.livedoor.jp/yu_ps13/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3249)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 5760)
s = Site.create(:name => %q#乃木坂46まとめ 乃木りんく#, 
  :url => 'http://nogizaka46link.blog.jp/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://nogizaka46link.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3224)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 24034)
s = Site.create(:name => %q#【韓国の反応】みずきの女子知韓宣言（´∀｀*)#, 
  :url => 'http://oboega-01.blog.jp/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://oboega-01.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3161)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 18026)
s = Site.create(:name => %q#バイク速報#, 
  :url => 'http://baiku-sokuho.info/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://baiku-sokuho.info/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3161)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 3236)
s = Site.create(:name => %q#ポリー速報#, 
  :url => 'http://blog.livedoor.jp/fightersmatome/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/fightersmatome/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3160)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 3066)
s = Site.create(:name => %q#ラビット速報#, 
  :url => 'http://rabitsokuhou.2chblog.jp/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://rabitsokuhou.2chblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3122)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 14177)
s = Site.create(:name => %q#筋肉速報#, 
  :url => 'http://kinsoku.blog.jp/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://kinsoku.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3090)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 5726)
# Site PAGE: 6/8 ----------------
s = Site.create(:name => %q#クズ速報#, 
  :url => 'http://kuzu-soku.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kuzu-soku.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3089)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 12800)
s = Site.create(:name => %q#2ch名人#, 
  :url => 'http://i2chmeijin.blog.fc2.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://i2chmeijin.blog.fc2.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3055)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1415)
s = Site.create(:name => %q#あらまめ2ch#, 
  :url => 'http://aramame.net', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://aramame.net/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3039)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 23652)
s = Site.create(:name => %q#ツバメ速報#, 
  :url => 'http://tsubamesoku.blog.jp/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://tsubamesoku.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3029)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 3012)
s = Site.create(:name => %q#はーとらいふ -出会い・子育て・生活系まとめ-#, 
  :url => 'http://heartlife-matome.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://heartlife-matome.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 3003)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 13199)
s = Site.create(:name => %q#芸能人の気になる噂#, 
  :url => 'http://blog.livedoor.jp/uwasainfo/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://blog.livedoor.jp/uwasainfo/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2942)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 22512)
s = Site.create(:name => %q#奥様は鬼女-DQN返しまとめ-#, 
  :url => 'http://okusama-kijyo.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://okusama-kijyo.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2894)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 14580)
s = Site.create(:name => %q#おたくみくす　声優まとめ#, 
  :url => 'http://otakumix.doorblog.jp/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://otakumix.doorblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2848)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 7749)
s = Site.create(:name => %q#たろそくWP#, 
  :url => 'http://tarosoku.com', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://tarosoku.com/?feed=rss2')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2739)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 9769)
s = Site.create(:name => %q#アイドルトレジャー#, 
  :url => 'http://www.aitore.com/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://www.aitore.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2679)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 11447)
s = Site.create(:name => %q#V系まとめ速報#, 
  :url => 'http://visual-matome.com', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://visual-matome.com/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2638)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6907)
s = Site.create(:name => %q#投資ちゃんねる - 株・FX・仮想通貨・投資2chまとめ -#, 
  :url => 'http://toushichannel.net/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://toushichannel.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2634)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 10716)
s = Site.create(:name => %q#鬼嫁ちゃんねる#, 
  :url => 'http://oniyomech.livedoor.biz/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://oniyomech.livedoor.biz/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2570)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 7411)
s = Site.create(:name => %q#日本人＿難民。～2ｃｈ読み物まとめ～#, 
  :url => 'http://nihonjinnanmin.com', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://nihonjinnanmin.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2553)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 15742)
s = Site.create(:name => %q#今日も荷物が届かない。@海外の反応#, 
  :url => 'http://baychannel.jp/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://baychannel.jp/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2542)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 17867)
s = Site.create(:name => %q#黒猫のウィズ　まとめ情報#, 
  :url => 'http://www.magicianwiz.net/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://www.magicianwiz.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2488)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 336)
s = Site.create(:name => %q#フットボール速報#, 
  :url => 'http://football-2ch.com/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://football-2ch.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2482)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 3854)
s = Site.create(:name => %q#ほのぼの動物速報 (Ф∀Ф)#, 
  :url => 'https://hnbn.fun', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'https://hnbn.fun/feed/')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2453)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 768)
s = Site.create(:name => %q#Zチャンネル＠VIP#, 
  :url => 'http://zch-vip.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://zch-vip.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2447)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 32636)
s = Site.create(:name => %q#NewsTimes#, 
  :url => 'http://nstimes.com', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://nstimes.com//nstimes.com/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2411)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 12340)
s = Site.create(:name => %q#NO FOOTY NO LIFE#, 
  :url => 'http://nofootynolife.blog.fc2.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://nofootynolife.blog.fc2.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2407)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6945)
s = Site.create(:name => %q#セロリのマリネ#, 
  :url => 'http://celery-marine.net', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://celery-marine.net/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2348)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 9902)
s = Site.create(:name => %q#ふぇー速#, 
  :url => 'http://fesoku.net/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://fesoku.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2328)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 21636)
s = Site.create(:name => %q#浮気ちゃんねる#, 
  :url => 'http://uwakich.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://uwakich.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2288)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 17099)
s = Site.create(:name => %q#スターライト速報 -遊戯王OCG情報まとめ-#, 
  :url => 'http://blog.livedoor.jp/maxut/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://blog.livedoor.jp/maxut/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2285)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1193)
# Site PAGE: 7/8 ----------------
s = Site.create(:name => %q#どうぶつちゃんねる#, 
  :url => 'http://animalch.net', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://animalch.net/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2265)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 4964)
s = Site.create(:name => %q#デジタルニューススレッド#, 
  :url => 'http://digital-thread.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://digital-thread.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2262)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 7163)
s = Site.create(:name => %q#虎速#, 
  :url => 'http://torasoku.blog.jp/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://torasoku.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2256)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 3772)
s = Site.create(:name => %q#すまいる(^-^)ぶろぐ#, 
  :url => 'http://blog.livedoor.jp/whoistrueenemy/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://blog.livedoor.jp/whoistrueenemy/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2251)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6763)
s = Site.create(:name => %q#ぱる速報#, 
  :url => 'http://parusoku.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://parusoku.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2219)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 9671)
s = Site.create(:name => %q#【海外の反応】タメナル#, 
  :url => 'http://tamenal.com', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://tamenal.com/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2205)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 15752)
s = Site.create(:name => %q#ネギ速#, 
  :url => 'http://www.negisoku.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://www.negisoku.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2193)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6569)
s = Site.create(:name => %q#〓 ねこメモ 〓#, 
  :url => 'http://nekomemo.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://nekomemo.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2187)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 2861)
s = Site.create(:name => %q#芸能-JAM-#, 
  :url => 'http://geinoujam.com/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://geinoujam.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2186)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 14385)
s = Site.create(:name => %q#乗り物速報#, 
  :url => 'http://norisoku.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://norisoku.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2160)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 9230)
s = Site.create(:name => %q#モナニュース#, 
  :url => 'http://mona-news.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://mona-news.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2144)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 10861)
s = Site.create(:name => %q#資格ちゃんねる#, 
  :url => 'http://shikaku2ch.doorblog.jp/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://shikaku2ch.doorblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2142)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 2847)
s = Site.create(:name => %q#easterEgg#, 
  :url => 'http://eegg.dip.jp/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://eegg.dip.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2128)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1245)
s = Site.create(:name => %q#PS4速報！#, 
  :url => 'http://openworldnews.net/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://openworldnews.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2119)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 2182)
s = Site.create(:name => %q#欅坂46まとめラボ#, 
  :url => 'http://www.keyakizaka46matomerabo.com', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://www.keyakizaka46matomerabo.com/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2089)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 5079)
s = Site.create(:name => %q#海外まとめネット#, 
  :url => 'http://kaigai-matome.net', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://kaigai-matome.net/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2052)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 11518)
s = Site.create(:name => %q#ネトウヨにゅーす。#, 
  :url => 'http://netouyonews.net/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://netouyonews.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2048)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6847)
s = Site.create(:name => %q#ヤクプラス#, 
  :url => 'http://yaku-plus.com', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://yaku-plus.com/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 2034)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 14268)
s = Site.create(:name => %q#もきゅ速(*´ω`*)人(´･ェ･｀)#, 
  :url => 'http://blog.livedoor.jp/aoba_f/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://blog.livedoor.jp/aoba_f/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1987)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6583)
s = Site.create(:name => %q#海外のお前ら　海外の反応#, 
  :url => 'http://blog.livedoor.jp/kaigainoomaera/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://blog.livedoor.jp/kaigainoomaera/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1980)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 23010)
s = Site.create(:name => %q#スロパチ乱舞#, 
  :url => 'http://slotmania222.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://slotmania222.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1975)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 2164)
s = Site.create(:name => %q#車速報#, 
  :url => 'http://vehicle123.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://vehicle123.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1949)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 3134)
s = Site.create(:name => %q#Ｇ速@読売ジャイアンツまとめブログ#, 
  :url => 'http://g-soku.blog.jp/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://g-soku.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1937)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1987)
s = Site.create(:name => %q#ラジック#, 
  :url => 'http://rajic.2chblog.jp/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://rajic.2chblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1929)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6112)
s = Site.create(:name => %q#パチンコ・パチスロ.com#, 
  :url => 'http://pachinkopachisro.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://pachinkopachisro.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1902)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 4821)
# Site PAGE: 8/8 ----------------
s = Site.create(:name => %q#イヤァオ！速報　プロレスまとめサイト#, 
  :url => 'http://iyaaaao.doorblog.jp/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://iyaaaao.doorblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1901)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1483)
s = Site.create(:name => %q#やみ速@なんJ西武まとめ#, 
  :url => 'http://blog.livedoor.jp/pawapuro_kouryaku/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/pawapuro_kouryaku/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1887)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 3061)
s = Site.create(:name => %q#せちがら速報-生活まとめブログ-#, 
  :url => 'http://www.sechigara.net/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://www.sechigara.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1873)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 12033)
s = Site.create(:name => %q#カルチョまとめブログ#, 
  :url => 'http://www.calciomatome.net/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://www.calciomatome.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1849)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1955)
s = Site.create(:name => %q#ゴールデンタイムズ#, 
  :url => 'http://blog.livedoor.jp/goldennews/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://blog.livedoor.jp/goldennews/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1818)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 5713)
s = Site.create(:name => %q#【海外の反応】まとめし#, 
  :url => 'http://matomeshi.net', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://matomeshi.net/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1817)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 9490)
s = Site.create(:name => %q#鬼嫁日記〜2ch生活まとめ〜#, 
  :url => 'http://oniyomediary.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://oniyomediary.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1796)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 7734)
s = Site.create(:name => %q#FGOまとめ速報#, 
  :url => 'https://www.fatego-matome.com', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'https://www.fatego-matome.com/feed/')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1788)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 2056)
s = Site.create(:name => %q#乃木坂46まとめたいよ#, 
  :url => 'http://nogizaka46.officeblog.jp/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://nogizaka46.officeblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1787)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 5394)
s = Site.create(:name => %q#鬼女まとめログ｜生活2chまとめブログ#, 
  :url => 'http://www.kijomatomelog.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://www.kijomatomelog.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1755)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 41035)
s = Site.create(:name => %q#登山ちゃんねる#, 
  :url => 'http://tozanchannel.blog.jp/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://tozanchannel.blog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1737)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 2637)
s = Site.create(:name => %q#チェックメイト | 2chまとめブログ#, 
  :url => 'http://checkmate-blog.com', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://checkmate-blog.com/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1730)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6078)
s = Site.create(:name => %q#watch＠２ちゃんねる#, 
  :url => 'http://www.watch2chan.com', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.watch2chan.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1729)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 4937)
s = Site.create(:name => %q#海外の反応 | 翻訳部#, 
  :url => 'http://kaigainohannou.info', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://kaigainohannou.info/feed/')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1718)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 16462)
s = Site.create(:name => %q#SSなび#, 
  :url => 'http://ss-navi.com/', 
  :category_id => category_name_binds['AA:SS'], 
  :feed_url => 'http://ss-navi.com/?xml')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1718)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1326)
s = Site.create(:name => %q#修羅バトル#, 
  :url => 'http://syurabattle.com', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://syurabattle.com//syurabattle.com/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1711)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 6430)
s = Site.create(:name => %q#うしみつ-2ch怖い話まとめ-#, 
  :url => 'http://usi32.com', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://usi32.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1708)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1948)
s = Site.create(:name => %q#本当にやった復讐　まとめ#, 
  :url => 'http://revenge.doorblog.jp/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://revenge.doorblog.jp/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1694)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 3006)
s = Site.create(:name => %q#ハロン棒ch　-競馬まとめ-#, 
  :url => 'http://haronbouchannel.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://haronbouchannel.com/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1676)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 1550)
s = Site.create(:name => %q#【つっ！.COM】 2chまとめにΣ(`・ω・ ´ )#, 
  :url => 'http://tuccom.com', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://tuccom.com/feed')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1674)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 8785)
s = Site.create(:name => %q#GOSSIP速報#, 
  :url => 'http://gossip1.net/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://gossip1.net/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1665)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 11852)
s = Site.create(:name => %q#台湾の反応 kaola.jp#, 
  :url => 'http://kaola.jp', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://kaola.jp/feed/')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1665)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 7843)
s = Site.create(:name => %q#PCパーツまとめ#, 
  :url => 'http://blog.livedoor.jp/bluejay01-review/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://blog.livedoor.jp/bluejay01-review/index.rdf')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1662)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 3226)
s = Site.create(:name => %q#でぃあんどる#, 
  :url => 'http://drdinl.com', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://drdinl.com/feed/')
DailyInCount.create(:count_date => 20190105, :site_id => s.id, :count => 1636)
DailyOutCount.create(:count_date => 20190105, :site_id => s.id, :count => 22323)
