# Generated by lib/tasks/moudamepo.rake
#  rake moudamepo:fetch > db/seeds.rb
#  generated at 2019-01-07 11:37:38 +0900

Category.create(:name => 'NEWS',
  :icon_url => 'http://sub.moudamepo.com/img/cate_10.png') # moudamepo's id = 10
Category.create(:name => 'VIP',
  :icon_url => 'http://sub.moudamepo.com/img/cate_11.png') # moudamepo's id = 11
Category.create(:name => '芸能',
  :icon_url => 'http://sub.moudamepo.com/img/cate_12.png') # moudamepo's id = 12
Category.create(:name => 'スポーツ',
  :icon_url => 'http://sub.moudamepo.com/img/cate_13.png') # moudamepo's id = 13
Category.create(:name => 'アニ漫',
  :icon_url => 'http://sub.moudamepo.com/img/cate_14.png') # moudamepo's id = 14
Category.create(:name => 'ゲーム',
  :icon_url => 'http://sub.moudamepo.com/img/cate_15.png') # moudamepo's id = 15
Category.create(:name => 'AA:SS',
  :icon_url => 'http://sub.moudamepo.com/img/cate_16.png') # moudamepo's id = 16
Category.create(:name => '生活',
  :icon_url => 'http://sub.moudamepo.com/img/cate_17.png') # moudamepo's id = 17
Category.create(:name => '翻訳',
  :icon_url => 'http://sub.moudamepo.com/img/cate_18.png') # moudamepo's id = 18
Category.create(:name => 'その他',
  :icon_url => 'http://sub.moudamepo.com/img/cate_19.png') # moudamepo's id = 19
# Mapping for moudamepo.com name to autoincrement id.
category_name_binds = {
  'NEWS' => 1,
  'VIP' => 2,
  '芸能' => 3,
  'スポーツ' => 4,
  'アニ漫' => 5,
  'ゲーム' => 6,
  'AA:SS' => 7,
  '生活' => 8,
  '翻訳' => 9,
  'その他' => 10,
}
# Mapping for moudamepo.com id to autoincrement id.
category_id_binds = {
  10 => 1,
  11 => 2,
  12 => 3,
  13 => 4,
  14 => 5,
  15 => 6,
  16 => 7,
  17 => 8,
  18 => 9,
  19 => 10,
}
# Site PAGE: 1/8 ----------------
s = Site.create(:name => %q#ポッカキット#, 
  :url => 'http://www.po-kaki-to.com', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://www.po-kaki-to.com/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2237.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2237.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 87376)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 212585)
s = Site.create(:name => %q#雪夜速報(●ﾟДﾟ●)TWINEWS！#, 
  :url => 'http://nadarenews.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://nadarenews.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2350.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2350.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 85154)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 424590)
s = Site.create(:name => %q#キニ速#, 
  :url => 'http://blog.livedoor.jp/kinisoku/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://blog.livedoor.jp/kinisoku/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2274.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2274.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 70562)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 102879)
s = Site.create(:name => %q#あじあニュースちゃんねる#, 
  :url => 'http://toua2chdqn.livedoor.blog/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://toua2chdqn.livedoor.blog/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1286.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1286.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 68035)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 289396)
s = Site.create(:name => %q#保守速報#, 
  :url => 'http://hosyusokuhou.jp', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://hosyusokuhou.jp/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1255.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1255.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 60078)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 121120)
s = Site.create(:name => %q#なんじぇいスタジアム＠なんJまとめ#, 
  :url => 'http://blog.livedoor.jp/nanjstu/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/nanjstu/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1165.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1165.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 56372)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 43037)
s = Site.create(:name => %q#大艦巨砲主義！#, 
  :url => 'http://military38.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://military38.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1069.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1069.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 54758)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 93274)
s = Site.create(:name => %q#暇つぶしニュース#, 
  :url => 'http://blog.livedoor.jp/rbkyn844/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://blog.livedoor.jp/rbkyn844/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1516.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1516.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 43335)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 109938)
s = Site.create(:name => %q#News U.S.#, 
  :url => 'http://news-us.org', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://news-us.org/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1426.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1426.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 40683)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 128162)
s = Site.create(:name => %q#アニゲー速報#, 
  :url => 'http://www.anige-sokuhouvip.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://www.anige-sokuhouvip.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1958.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1958.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 37725)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 106146)
s = Site.create(:name => %q#不思議.net#, 
  :url => 'http://world-fusigi.net/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://world-fusigi.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2211.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2211.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 35611)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 34724)
s = Site.create(:name => %q#NEWSまとめもりー｜2chまとめブログ#, 
  :url => 'http://www.akb48matomemory.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.akb48matomemory.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2034.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2034.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 35312)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 114721)
s = Site.create(:name => %q#なんJ PRIDE#, 
  :url => 'http://blog.livedoor.jp/rock1963roll/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/rock1963roll/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1414.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1414.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 31109)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 31992)
s = Site.create(:name => %q#ぴこ速(〃'∇'〃)？#, 
  :url => 'https://pioncoo.net', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'https://pioncoo.net/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2143.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2143.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 30363)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 132125)
s = Site.create(:name => %q#かぞくちゃんねる#, 
  :url => 'http://kazokuchannel.doorblog.jp/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kazokuchannel.doorblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1961.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1961.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 26607)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 79708)
s = Site.create(:name => %q#U-1 NEWS#, 
  :url => 'http://japannews01.blog.jp/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://japannews01.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1519.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1519.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 25719)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 118362)
s = Site.create(:name => %q#【海外の反応】　パンドラの憂鬱#, 
  :url => 'http://kaigainohannoublog.blog55.fc2.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://kaigainohannoublog.blog55.fc2.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1846.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1846.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 25493)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 62186)
s = Site.create(:name => %q#軍事・ミリタリー速報☆彡#, 
  :url => 'http://blog.livedoor.jp/corez18c24-mili777/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://blog.livedoor.jp/corez18c24-mili777/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2114.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2114.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 24170)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 51623)
s = Site.create(:name => %q#Nニュースα#, 
  :url => 'http://nnews1.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://nnews1.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2247.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2247.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 19874)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 174880)
s = Site.create(:name => %q#おーるじゃんる#, 
  :url => 'http://crx7601.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://crx7601.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1599.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1599.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 19458)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 61249)
s = Site.create(:name => %q#もえるあじあ(･∀･)#, 
  :url => 'http://www.moeruasia.net', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.moeruasia.net/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1972.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1972.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 18540)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 95126)
s = Site.create(:name => %q#VIPワイドガイド#, 
  :url => 'http://news4wide.livedoor.biz/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://news4wide.livedoor.biz/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1976.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1976.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 17989)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 69826)
s = Site.create(:name => %q#きらりちゃんねる ～修羅場・鬼女・生活2chまとめ～#, 
  :url => 'http://kirari-ch.blog.jp/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kirari-ch.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2389.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2389.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 17923)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 51693)
s = Site.create(:name => %q#修羅場ハザード -復讐・DQN返し・衝撃系まとめ-#, 
  :url => 'http://syurabahazard.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://syurabahazard.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1980.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1980.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 17655)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 54580)
s = Site.create(:name => %q#オーバージョイド！　　2chまとめサイト#, 
  :url => 'http://overjoyed.info', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://overjoyed.info/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2360.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2360.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 17380)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 60833)
# Site PAGE: 2/8 ----------------
s = Site.create(:name => %q#妹はVIPPER#, 
  :url => 'http://vipsister23.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://vipsister23.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2258.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2258.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 17135)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 91762)
s = Site.create(:name => %q#あ艦これ ～艦隊これくしょんまとめブログ～#, 
  :url => 'http://akankore.doorblog.jp/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://akankore.doorblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1954.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1954.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 16315)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 14450)
s = Site.create(:name => %q#衝撃体験！アンビリバボー｜浮気・不倫・修羅場・離婚#, 
  :url => 'http://uwakitaiken.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://uwakitaiken.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2318.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2318.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 15489)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 54285)
s = Site.create(:name => %q#まじかる☆にゅーす#, 
  :url => 'http://magical-news.blog.jp/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://magical-news.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2314.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2314.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 15347)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 59436)
s = Site.create(:name => %q#日刊やきう速報＠野球まとめ#, 
  :url => 'http://blog.livedoor.jp/yakiusoku/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/yakiusoku/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1944.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1944.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 15056)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 17063)
s = Site.create(:name => %q#世界の憂鬱  海外・韓国の反応#, 
  :url => 'http://blog.livedoor.jp/sekaiminzoku/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://blog.livedoor.jp/sekaiminzoku/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1675.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1675.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 13718)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 56530)
s = Site.create(:name => %q#ジャンプまとめ速報#, 
  :url => 'http://jumpmatome2ch.biz', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://jumpmatome2ch.biz/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1667.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1667.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 13708)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 24380)
s = Site.create(:name => %q#女子アナお宝画像速報#, 
  :url => 'http://blog.livedoor.jp/a_load/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://blog.livedoor.jp/a_load/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2174.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2174.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 13053)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 80655)
s = Site.create(:name => %q#1000mg#, 
  :url => 'http://1000mg.jp', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://1000mg.jp/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2181.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2181.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 12562)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 13660)
s = Site.create(:name => %q#GUNDAM.LOG｜ガンダムまとめブログ#, 
  :url => 'http://gundamlog.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://gundamlog.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1709.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1709.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 12545)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 19566)
s = Site.create(:name => %q#乃木坂46まとめ 1/46#, 
  :url => 'http://nogizaka-46bunno1.blog.jp/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://nogizaka-46bunno1.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2282.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2282.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 12167)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 25898)
s = Site.create(:name => %q#暇人＼(^o^)／速報#, 
  :url => 'http://himasoku.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://himasoku.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2074.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2074.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 12064)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 34698)
s = Site.create(:name => %q#AKB48タイムズ（AKB48まとめ）#, 
  :url => 'http://akb48taimuzu.livedoor.biz/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://akb48taimuzu.livedoor.biz/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2121.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2121.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 11204)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 15497)
s = Site.create(:name => %q#乃木坂46まとめもらんだむ|乃木坂46・欅坂46まとめ速報#, 
  :url => 'http://nogizaka46matome.2chblog.jp/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://nogizaka46matome.2chblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2256.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2256.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 10838)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 23017)
s = Site.create(:name => %q# じゃぱそく！#, 
  :url => 'http://jpsoku.blog.jp/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://jpsoku.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2165.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2165.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 10258)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 29607)
s = Site.create(:name => %q#でっちでち速報#, 
  :url => 'http://dechisoku.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://dechisoku.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2393.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2393.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 9891)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 18009)
s = Site.create(:name => %q#seiyu fan#, 
  :url => 'http://seiyufan.livedoor.biz/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://seiyufan.livedoor.biz/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2386.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2386.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 9789)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 26384)
s = Site.create(:name => %q#芸能かめはめ波#, 
  :url => 'http://geinoukame.blog.fc2.com/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://geinoukame.blog.fc2.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2098.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2098.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 9717)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 57690)
s = Site.create(:name => %q# /)；｀ω´)＜国家総動員報#, 
  :url => 'http://totalwar.doorblog.jp/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://totalwar.doorblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2220.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2220.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 9506)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 72156)
s = Site.create(:name => %q#阪神タイガースちゃんねる#, 
  :url => 'http://hanshintigers1.blog.jp/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://hanshintigers1.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1981.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1981.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 9497)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 24365)
s = Site.create(:name => %q#エクサワロス | ニュース系2chまとめブログ#, 
  :url => 'http://exawarosu.net/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://exawarosu.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1872.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1872.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 9312)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 67986)
s = Site.create(:name => %q#カイカイ反応通信#, 
  :url => 'http://blog.livedoor.jp/kaikaihanno/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://blog.livedoor.jp/kaikaihanno/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1495.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1495.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 9240)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 30097)
s = Site.create(:name => %q#正義の見方#, 
  :url => 'http://www.honmotakeshi.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.honmotakeshi.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2169.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2169.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 9227)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 37410)
s = Site.create(:name => %q#ワロタニッキ#, 
  :url => 'http://warotanikki.com', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://warotanikki.com/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2051.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2051.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 8717)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 24333)
# Site PAGE: 3/8 ----------------
s = Site.create(:name => %q#NEWS+α#, 
  :url => 'http://newsplusalpha.net/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://newsplusalpha.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2345.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2345.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 8687)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 23145)
s = Site.create(:name => %q#厳選！韓国情報#, 
  :url => 'http://gensen2ch.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://gensen2ch.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2036.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2036.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 8645)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 29851)
s = Site.create(:name => %q#キムチ速報#, 
  :url => 'http://kimsoku.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://kimsoku.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1187.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1187.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 8308)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 38692)
s = Site.create(:name => %q#なんJ（まとめては）いかんのか？#, 
  :url => 'http://blog.livedoor.jp/livejupiter2/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/livejupiter2/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2020.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2020.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 8221)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 5715)
s = Site.create(:name => %q#ぶる速-VIP#, 
  :url => 'http://burusoku-vip.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://burusoku-vip.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2008.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2008.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 7973)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 30070)
s = Site.create(:name => %q#NOGIVIOLA＠乃木坂46まとめ#, 
  :url => 'http://nogiviola.livedoor.biz/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://nogiviola.livedoor.biz/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2307.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2307.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 7871)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 16573)
s = Site.create(:name => %q#チラ速 (*￣ω￣)/ -画像2chまとめブログ-#, 
  :url => 'http://blog.livedoor.jp/nichmatomerunn/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://blog.livedoor.jp/nichmatomerunn/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1966.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1966.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 7749)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 39944)
s = Site.create(:name => %q#ヒーローNEWS#, 
  :url => 'http://hero-news.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://hero-news.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2371.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2371.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 7364)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 8366)
s = Site.create(:name => %q#笑　韓　ブログ#, 
  :url => 'http://www.wara2ch.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.wara2ch.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1778.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1778.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 7348)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 16208)
s = Site.create(:name => %q#fig速#, 
  :url => 'http://figsoku.net', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://figsoku.net/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2021.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2021.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 7253)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 6575)
s = Site.create(:name => %q#ニコニコVIP2ch#, 
  :url => 'http://blog.livedoor.jp/nicovip2ch/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://blog.livedoor.jp/nicovip2ch/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2228.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2228.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 7244)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 67900)
s = Site.create(:name => %q#スコールちゃんねる｜２ちゃんまとめブログ#, 
  :url => 'http://squallchannel.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://squallchannel.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2014.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2014.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 7218)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 17595)
s = Site.create(:name => %q#素敵な鬼女様#, 
  :url => 'http://sutekinakijo.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://sutekinakijo.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1562.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1562.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 7202)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 21126)
s = Site.create(:name => %q#鬼女はみた -修羅場・恋愛・育児系まとめサイト-#, 
  :url => 'http://kijyomita.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kijyomita.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1931.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1931.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 7105)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 21405)
s = Site.create(:name => %q#かんむす！-艦隊これくしょんまとめブログ-#, 
  :url => 'http://kanmsu.com', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://kanmsu.com/?feed=rss2',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1967.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1967.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 6855)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 8731)
s = Site.create(:name => %q#海外の万国反応記＠海外の反応#, 
  :url => 'http://www.all-nationz.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://www.all-nationz.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2060.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2060.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 6590)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 24661)
s = Site.create(:name => %q#おにひめちゃんの監視部屋-鬼女、キチママ、修羅場、生活まとめ-#, 
  :url => 'http://onihimechan.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://onihimechan.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1902.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1902.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 6569)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 20664)
s = Site.create(:name => %q#どんぐりこ - 海外の反応#, 
  :url => 'http://dng65.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://dng65.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1962.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1962.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 6430)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 27218)
s = Site.create(:name => %q#艦これ速報　艦隊これくしょんまとめ#, 
  :url => 'http://kancolle.doorblog.jp/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://kancolle.doorblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1928.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1928.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 6374)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 8164)
s = Site.create(:name => %q#キチガイママまとめ保管庫#, 
  :url => 'http://www.kitimama-matome.net/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://www.kitimama-matome.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1093.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1093.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 6004)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 9878)
s = Site.create(:name => %q#ムダスレ無き改革#, 
  :url => 'http://mudasure.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://mudasure.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2243.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2243.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5989)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 12747)
s = Site.create(:name => %q#セロリのきんぴら#, 
  :url => 'http://celery.diary.to/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://celery.diary.to/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2186.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2186.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5980)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 9729)
s = Site.create(:name => %q#まるごと速報#, 
  :url => 'http://maru-soku.com', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://maru-soku.com/?feed=rss2',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2369.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2369.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5935)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 20589)
s = Site.create(:name => %q#最強ジャンプ放送局#, 
  :url => 'http://www.saikyo-jump.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://www.saikyo-jump.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2277.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2277.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5824)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 14092)
s = Site.create(:name => %q#鬼女まとめ速報 -修羅場・キチママ・生活まとめ-#, 
  :url => 'http://kijyomatome.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kijyomatome.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1587.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1587.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5809)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 21189)
# Site PAGE: 4/8 ----------------
s = Site.create(:name => %q#アナきゃぷ速報#, 
  :url => 'http://anacap.doorblog.jp/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://anacap.doorblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2176.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2176.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5771)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 10455)
s = Site.create(:name => %q#思考ちゃんねる#, 
  :url => 'http://mindhack2ch.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://mindhack2ch.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2126.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2126.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5710)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 43906)
s = Site.create(:name => %q#【2ch】ニュー速クオリティ#, 
  :url => 'http://news4vip.livedoor.biz/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://news4vip.livedoor.biz/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2142.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2142.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5599)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 18894)
s = Site.create(:name => %q#スロ板-RUSH#, 
  :url => 'http://fiveslot777.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://fiveslot777.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2242.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2242.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5592)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 6158)
s = Site.create(:name => %q#気になった生活スレまとめ#, 
  :url => 'http://kininatta2chmatome.doorblog.jp/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kininatta2chmatome.doorblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1247.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1247.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5563)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 11147)
s = Site.create(:name => %q#­海外反応　キキミミ#, 
  :url => 'http://xxxkikimimixxx.blog.fc2.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://xxxkikimimixxx.blog.fc2.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2157.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2157.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5527)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 36007)
s = Site.create(:name => %q#まにゅそく 2chまとめニュース速報VIP#, 
  :url => 'http://2ch-matomenews.com', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://2ch-matomenews.com/feed/',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1725.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1725.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5492)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 37473)
s = Site.create(:name => %q#修羅場まとめ速報#, 
  :url => 'http://shuraba-matome.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://shuraba-matome.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1919.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1919.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5474)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 23317)
s = Site.create(:name => %q#政経ワロスまとめニュース♪#, 
  :url => 'http://seikeidouga.blog.jp/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://seikeidouga.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2309.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2309.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5345)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 44436)
s = Site.create(:name => %q#ニュース30over#, 
  :url => 'http://www.news30over.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.news30over.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1614.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1614.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5121)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 19645)
s = Site.create(:name => %q#SS 森きのこ！#, 
  :url => 'http://morikinoko.com/', 
  :category_id => category_name_binds['AA:SS'], 
  :feed_url => 'http://morikinoko.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1032.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1032.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5093)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1605)
s = Site.create(:name => %q#【2ch】コピペ情報局#, 
  :url => 'http://news.2chblog.jp/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://news.2chblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2200.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2200.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 5029)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 21691)
s = Site.create(:name => %q#政経ch#, 
  :url => 'http://fxya.blog129.fc2.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://fxya.blog129.fc2.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1080.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1080.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4950)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 22144)
s = Site.create(:name => %q#みんなの暇つぶし#, 
  :url => 'http://minnanohimatubushi.2chblog.jp/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://minnanohimatubushi.2chblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1318.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1318.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4924)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 24128)
s = Site.create(:name => %q#まとめたニュース#, 
  :url => 'http://matometanews.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://matometanews.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2066.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2066.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4729)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 38992)
s = Site.create(:name => %q#億ったー#, 
  :url => 'http://www.okutta.net/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.okutta.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2251.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2251.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4554)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 36409)
s = Site.create(:name => %q#気団まとめ-噫無情-｜嫁・浮気・メシマズ#, 
  :url => 'http://kidan-m.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kidan-m.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1788.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1788.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4327)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 16592)
s = Site.create(:name => %q#パズ速 -パズドラ情報まとめ-#, 
  :url => 'http://pazusoku.blog.fc2.com/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://pazusoku.blog.fc2.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2203.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2203.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4327)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1112)
s = Site.create(:name => %q#渡る世間はキチばかり - 鬼女・修羅場・キチママ・義家族まとめ-#, 
  :url => 'http://watarukiti.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://watarukiti.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2379.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2379.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4267)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 12851)
s = Site.create(:name => %q#鯉速＠広島東洋カープまとめブログ#, 
  :url => 'http://koisoku.ldblog.jp/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://koisoku.ldblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2028.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2028.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4232)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1322)
s = Site.create(:name => %q#子育てちゃんねる#, 
  :url => 'http://kosodatech.blog133.fc2.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://feeds.fc2.com/fc2/xml?host=kosodatech.blog133',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1368.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1368.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4107)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 7310)
s = Site.create(:name => %q#ちゃん速#, 
  :url => 'http://chansoku.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://chansoku.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2362.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2362.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4055)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 10964)
s = Site.create(:name => %q#2ch東方スレ観測所#, 
  :url => 'http://blog.livedoor.jp/coleblog/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://blog.livedoor.jp/coleblog/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2179.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2179.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4042)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1190)
s = Site.create(:name => %q#基地沢直樹-復讐・修羅場・DQN返し【2chスカッとする話まとめ...#, 
  :url => 'http://kitizawa.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kitizawa.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2073.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2073.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4031)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 12502)
# Site PAGE: 5/8 ----------------
s = Site.create(:name => %q#竜速（りゅうそく）#, 
  :url => 'http://blog.livedoor.jp/bbyakyu/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/bbyakyu/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1997.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1997.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 4011)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 2351)
s = Site.create(:name => %q#ガールズVIPまとめ#, 
  :url => 'http://girlsvip-matome.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://girlsvip-matome.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2100.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2100.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3936)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 12766)
s = Site.create(:name => %q#ガハろぐNewsヽ(･ω･)/ｽﾞｺｰ#, 
  :url => 'http://gahalog.2chblog.jp/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://gahalog.2chblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2405.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2405.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3933)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 13724)
s = Site.create(:name => %q#(*ﾟ∀ﾟ)ゞカガクニュース隊#, 
  :url => 'http://www.scienceplus2ch.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://www.scienceplus2ch.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2132.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2132.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3749)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 17397)
s = Site.create(:name => %q#おたほー#, 
  :url => 'http://blog.livedoor.jp/otataho/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://blog.livedoor.jp/otataho/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1552.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1552.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3707)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 12673)
s = Site.create(:name => %q#鬼女梅#, 
  :url => 'http://kijoume.net/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kijoume.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2409.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2409.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3705)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 11258)
s = Site.create(:name => %q#それからの出来事() アイマスまとめ#, 
  :url => 'http://sorekarano.blomaga.jp/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://sorekarano.blomaga.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2117.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2117.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3665)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 2378)
s = Site.create(:name => %q#欅坂46まとめもり～#, 
  :url => 'http://keyakizaka46matomemory.net/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://keyakizaka46matomemory.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2347.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2347.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3613)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 5922)
s = Site.create(:name => %q#働くモノニュース : 人生VIP職人ブログwww#, 
  :url => 'http://workingnews.blog117.fc2.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://workingnews.blog117.fc2.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1232.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1232.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3610)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 6461)
s = Site.create(:name => %q#スロログ#, 
  :url => 'http://slotlog.net/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://slotlog.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2387.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2387.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3575)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 3644)
s = Site.create(:name => %q#V速ニュップ#, 
  :url => 'http://www.vsnp.net/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://www.vsnp.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2248.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2248.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3439)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 9909)
s = Site.create(:name => %q#かんこく！　韓国の反応翻訳ブログ#, 
  :url => 'http://kankokunohannou.org/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://kankokunohannou.org/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2048.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2048.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3274)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 26724)
s = Site.create(:name => %q#虹神速報-にじそく#, 
  :url => 'http://nizigami.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://nizigami.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1230.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1230.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3260)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 5999)
s = Site.create(:name => %q#FX2ちゃんねる|投資系2chまとめ#, 
  :url => 'http://www.fx2ch.net', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://www.fx2ch.net/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1183.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1183.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3228)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 2222)
s = Site.create(:name => %q#乃木坂46まとめ 乃木りんく#, 
  :url => 'http://nogizaka46link.blog.jp/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://nogizaka46link.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2388.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2388.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3212)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 22910)
s = Site.create(:name => %q#バイク速報#, 
  :url => 'http://baiku-sokuho.info/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://baiku-sokuho.info/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2007.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2007.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3177)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 3045)
s = Site.create(:name => %q#ニュー速VIPブログ(`･ω･´)#, 
  :url => 'http://blog.livedoor.jp/insidears/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://blog.livedoor.jp/insidears/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2029.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2029.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3171)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 3156)
s = Site.create(:name => %q#（　｀ハ´）中国の反応ブログ#, 
  :url => 'http://asiareaction.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://asiareaction.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1858.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1858.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3145)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 11986)
s = Site.create(:name => %q#ああ言えばForYou#, 
  :url => 'http://aaieba.livedoor.biz/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://aaieba.livedoor.biz/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2105.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2105.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3144)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 5387)
s = Site.create(:name => %q#あらまめ2ch#, 
  :url => 'http://aramame.net', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://aramame.net/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1472.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1472.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3126)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 21217)
s = Site.create(:name => %q#海外の反応　お隣速報#, 
  :url => 'http://www.otonarisoku.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://www.otonarisoku.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1920.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1920.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3102)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 25115)
s = Site.create(:name => %q#ラビット速報#, 
  :url => 'http://rabitsokuhou.2chblog.jp/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://rabitsokuhou.2chblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1378.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1378.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3095)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 14043)
s = Site.create(:name => %q#ゆめ痛 -NEWS ALERT-#, 
  :url => 'http://blog.livedoor.jp/yu_ps13/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://blog.livedoor.jp/yu_ps13/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2065.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2065.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 3085)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 5367)
s = Site.create(:name => %q#ポリー速報#, 
  :url => 'http://blog.livedoor.jp/fightersmatome/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/fightersmatome/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1697.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1697.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2976)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 2884)
s = Site.create(:name => %q#クズ速報#, 
  :url => 'http://kuzu-soku.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://kuzu-soku.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2278.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2278.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2974)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 12051)
# Site PAGE: 6/8 ----------------
s = Site.create(:name => %q#筋肉速報#, 
  :url => 'http://kinsoku.blog.jp/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://kinsoku.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2232.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2232.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2969)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 5398)
s = Site.create(:name => %q#芸能人の気になる噂#, 
  :url => 'http://blog.livedoor.jp/uwasainfo/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://blog.livedoor.jp/uwasainfo/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1805.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1805.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2967)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 20968)
s = Site.create(:name => %q#【韓国の反応】みずきの女子知韓宣言（´∀｀*)#, 
  :url => 'http://oboega-01.blog.jp/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://oboega-01.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1837.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1837.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2966)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 15787)
s = Site.create(:name => %q#2ch名人#, 
  :url => 'http://i2chmeijin.blog.fc2.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://i2chmeijin.blog.fc2.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2354.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2354.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2929)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1261)
s = Site.create(:name => %q#はーとらいふ -出会い・子育て・生活系まとめ-#, 
  :url => 'http://heartlife-matome.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://heartlife-matome.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1951.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1951.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2925)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 12872)
s = Site.create(:name => %q#ツバメ速報#, 
  :url => 'http://tsubamesoku.blog.jp/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://tsubamesoku.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2127.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2127.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2909)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 2761)
s = Site.create(:name => %q#おたくみくす　声優まとめ#, 
  :url => 'http://otakumix.doorblog.jp/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://otakumix.doorblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2227.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2227.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2840)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 7611)
s = Site.create(:name => %q#奥様は鬼女-DQN返しまとめ-#, 
  :url => 'http://okusama-kijyo.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://okusama-kijyo.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1881.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1881.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2792)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 14343)
s = Site.create(:name => %q#たろそくWP#, 
  :url => 'http://tarosoku.com', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://tarosoku.com/?feed=rss2',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2363.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2363.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2740)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 9353)
s = Site.create(:name => %q#ほのぼの動物速報 (Ф∀Ф)#, 
  :url => 'https://hnbn.fun', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'https://hnbn.fun/feed/',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2411.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2411.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2677)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 884)
s = Site.create(:name => %q#V系まとめ速報#, 
  :url => 'http://visual-matome.com', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://visual-matome.com/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2090.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2090.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2607)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 6725)
s = Site.create(:name => %q#アイドルトレジャー#, 
  :url => 'http://www.aitore.com/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://www.aitore.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2046.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2046.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2601)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 10642)
s = Site.create(:name => %q#鬼嫁ちゃんねる#, 
  :url => 'http://oniyomech.livedoor.biz/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://oniyomech.livedoor.biz/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1089.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1089.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2458)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 6909)
s = Site.create(:name => %q#フットボール速報#, 
  :url => 'http://football-2ch.com/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://football-2ch.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1848.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1848.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2384)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 3790)
s = Site.create(:name => %q#NewsTimes#, 
  :url => 'http://nstimes.com', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://nstimes.com//nstimes.com/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2160.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2160.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2372)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 11886)
s = Site.create(:name => %q#投資ちゃんねる - 株・FX・仮想通貨・投資2chまとめ -#, 
  :url => 'http://toushichannel.net/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://toushichannel.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2315.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2315.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2369)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 9835)
s = Site.create(:name => %q#今日も荷物が届かない。@海外の反応#, 
  :url => 'http://baychannel.jp/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://baychannel.jp/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2404.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2404.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2362)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 17057)
s = Site.create(:name => %q#Zチャンネル＠VIP#, 
  :url => 'http://zch-vip.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://zch-vip.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1028.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1028.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2361)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 30956)
s = Site.create(:name => %q#NO FOOTY NO LIFE#, 
  :url => 'http://nofootynolife.blog.fc2.com/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://nofootynolife.blog.fc2.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1294.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1294.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2341)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 6695)
s = Site.create(:name => %q#日本人＿難民。～2ｃｈ読み物まとめ～#, 
  :url => 'http://nihonjinnanmin.com', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://nihonjinnanmin.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2045.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2045.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2329)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 14829)
s = Site.create(:name => %q#黒猫のウィズ　まとめ情報#, 
  :url => 'http://www.magicianwiz.net/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://www.magicianwiz.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2089.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2089.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2324)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 314)
s = Site.create(:name => %q#すまいる(^-^)ぶろぐ#, 
  :url => 'http://blog.livedoor.jp/whoistrueenemy/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://blog.livedoor.jp/whoistrueenemy/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2244.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2244.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2276)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 6859)
s = Site.create(:name => %q#セロリのマリネ#, 
  :url => 'http://celery-marine.net', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://celery-marine.net/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2365.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2365.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2228)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 8867)
s = Site.create(:name => %q#ぱる速報#, 
  :url => 'http://parusoku.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://parusoku.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1491.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1491.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2196)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 9297)
s = Site.create(:name => %q#ふぇー速#, 
  :url => 'http://fesoku.net/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://fesoku.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1283.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1283.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2176)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 20209)
# Site PAGE: 7/8 ----------------
s = Site.create(:name => %q#浮気ちゃんねる#, 
  :url => 'http://uwakich.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://uwakich.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2010.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2010.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2159)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 15150)
s = Site.create(:name => %q#【海外の反応】タメナル#, 
  :url => 'http://tamenal.com', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://tamenal.com/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2166.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2166.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2156)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 17532)
s = Site.create(:name => %q#虎速#, 
  :url => 'http://torasoku.blog.jp/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://torasoku.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2217.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2217.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2146)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 3898)
s = Site.create(:name => %q#スターライト速報 -遊戯王OCG情報まとめ-#, 
  :url => 'http://blog.livedoor.jp/maxut/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://blog.livedoor.jp/maxut/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1631.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1631.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2138)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1140)
s = Site.create(:name => %q#どうぶつちゃんねる#, 
  :url => 'http://animalch.net', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://animalch.net/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1249.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1249.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2135)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 4398)
s = Site.create(:name => %q#ネギ速#, 
  :url => 'http://www.negisoku.com/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://www.negisoku.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2275.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2275.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2126)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 6572)
s = Site.create(:name => %q#〓 ねこメモ 〓#, 
  :url => 'http://nekomemo.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://nekomemo.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1564.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1564.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2123)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 2464)
s = Site.create(:name => %q#芸能-JAM-#, 
  :url => 'http://geinoujam.com/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://geinoujam.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2292.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2292.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2110)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 14171)
s = Site.create(:name => %q#資格ちゃんねる#, 
  :url => 'http://shikaku2ch.doorblog.jp/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://shikaku2ch.doorblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1370.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1370.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2083)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 2746)
s = Site.create(:name => %q#海外まとめネット#, 
  :url => 'http://kaigai-matome.net', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://kaigai-matome.net/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2171.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2171.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2071)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 10956)
s = Site.create(:name => %q#デジタルニューススレッド#, 
  :url => 'http://digital-thread.com/', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://digital-thread.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1974.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1974.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2067)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 6799)
s = Site.create(:name => %q#PS4速報！#, 
  :url => 'http://openworldnews.net/', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'http://openworldnews.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2201.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2201.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2049)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1939)
s = Site.create(:name => %q#乗り物速報#, 
  :url => 'http://norisoku.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://norisoku.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1949.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1949.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2046)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 8491)
s = Site.create(:name => %q#ネトウヨにゅーす。#, 
  :url => 'http://netouyonews.net/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://netouyonews.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1873.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1873.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 2024)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 7096)
s = Site.create(:name => %q#欅坂46まとめラボ#, 
  :url => 'http://www.keyakizaka46matomerabo.com', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://www.keyakizaka46matomerabo.com/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2359.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2359.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1969)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 4702)
s = Site.create(:name => %q#うしみつ-2ch怖い話まとめ-#, 
  :url => 'http://usi32.com', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://usi32.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2392.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2392.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1961)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1960)
s = Site.create(:name => %q#モナニュース#, 
  :url => 'http://mona-news.com/', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://mona-news.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2264.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2264.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1950)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 9732)
s = Site.create(:name => %q#easterEgg#, 
  :url => 'http://eegg.dip.jp/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://eegg.dip.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1027.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1027.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1949)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1219)
s = Site.create(:name => %q#Ｇ速@読売ジャイアンツまとめブログ#, 
  :url => 'http://g-soku.blog.jp/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://g-soku.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2391.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2391.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1942)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1981)
s = Site.create(:name => %q#もきゅ速(*´ω`*)人(´･ェ･｀)#, 
  :url => 'http://blog.livedoor.jp/aoba_f/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://blog.livedoor.jp/aoba_f/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1133.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1133.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1937)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 6149)
s = Site.create(:name => %q#車速報#, 
  :url => 'http://vehicle123.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://vehicle123.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2302.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2302.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1876)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 2835)
s = Site.create(:name => %q#イヤァオ！速報　プロレスまとめサイト#, 
  :url => 'http://iyaaaao.doorblog.jp/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://iyaaaao.doorblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2303.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2303.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1874)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1409)
s = Site.create(:name => %q#パチンコ・パチスロ.com#, 
  :url => 'http://pachinkopachisro.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://pachinkopachisro.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1790.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1790.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1858)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 4707)
s = Site.create(:name => %q#海外のお前ら　海外の反応#, 
  :url => 'http://blog.livedoor.jp/kaigainoomaera/', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://blog.livedoor.jp/kaigainoomaera/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1879.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1879.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1854)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 20754)
s = Site.create(:name => %q#スロパチ乱舞#, 
  :url => 'http://slotmania222.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://slotmania222.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2308.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2308.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1829)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 2077)
# Site PAGE: 8/8 ----------------
s = Site.create(:name => %q#ゴールデンタイムズ#, 
  :url => 'http://blog.livedoor.jp/goldennews/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://blog.livedoor.jp/goldennews/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1929.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1929.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1826)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 5540)
s = Site.create(:name => %q#ラジック#, 
  :url => 'http://rajic.2chblog.jp/', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://rajic.2chblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1514.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1514.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1818)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 6048)
s = Site.create(:name => %q#やみ速@なんJ西武まとめ#, 
  :url => 'http://blog.livedoor.jp/pawapuro_kouryaku/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://blog.livedoor.jp/pawapuro_kouryaku/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2293.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2293.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1809)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 2852)
s = Site.create(:name => %q#【海外の反応】まとめし#, 
  :url => 'http://matomeshi.net', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://matomeshi.net/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2343.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2343.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1791)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 9675)
s = Site.create(:name => %q#カルチョまとめブログ#, 
  :url => 'http://www.calciomatome.net/', 
  :category_id => category_name_binds['スポーツ'], 
  :feed_url => 'http://www.calciomatome.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1145.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1145.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1776)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1836)
s = Site.create(:name => %q#せちがら速報-生活まとめブログ-#, 
  :url => 'http://www.sechigara.net/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://www.sechigara.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2135.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2135.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1763)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 11419)
s = Site.create(:name => %q#修羅バトル#, 
  :url => 'http://syurabattle.com', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://syurabattle.com//syurabattle.com/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2269.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2269.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1730)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 6463)
s = Site.create(:name => %q#SSなび#, 
  :url => 'http://ss-navi.com/', 
  :category_id => category_name_binds['AA:SS'], 
  :feed_url => 'http://ss-navi.com/?xml',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2370.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2370.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1730)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1354)
s = Site.create(:name => %q#チェックメイト | 2chまとめブログ#, 
  :url => 'http://checkmate-blog.com', 
  :category_id => category_name_binds['アニ漫'], 
  :feed_url => 'http://checkmate-blog.com/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2150.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2150.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1721)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 5756)
s = Site.create(:name => %q#乃木坂46まとめたいよ#, 
  :url => 'http://nogizaka46.officeblog.jp/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://nogizaka46.officeblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2397.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2397.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1720)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 4705)
s = Site.create(:name => %q#鬼嫁日記〜2ch生活まとめ〜#, 
  :url => 'http://oniyomediary.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://oniyomediary.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2063.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2063.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1711)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 7338)
s = Site.create(:name => %q#ヤクプラス#, 
  :url => 'http://yaku-plus.com', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://yaku-plus.com/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2401.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2401.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1701)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 12759)
s = Site.create(:name => %q#海外の反応 | 翻訳部#, 
  :url => 'http://kaigainohannou.info', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://kaigainohannou.info/feed/',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2285.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2285.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1697)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 15918)
s = Site.create(:name => %q#ハロン棒ch　-競馬まとめ-#, 
  :url => 'http://haronbouchannel.com/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://haronbouchannel.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2296.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2296.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1697)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1545)
s = Site.create(:name => %q#鬼女まとめログ｜生活2chまとめブログ#, 
  :url => 'http://www.kijomatomelog.com/', 
  :category_id => category_name_binds['生活'], 
  :feed_url => 'http://www.kijomatomelog.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2173.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2173.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1682)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 38638)
s = Site.create(:name => %q#登山ちゃんねる#, 
  :url => 'http://tozanchannel.blog.jp/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://tozanchannel.blog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2167.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2167.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1677)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 2495)
s = Site.create(:name => %q#FGOまとめ速報#, 
  :url => 'https://www.fatego-matome.com', 
  :category_id => category_name_binds['ゲーム'], 
  :feed_url => 'https://www.fatego-matome.com/feed/',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2394.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2394.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1638)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 1963)
s = Site.create(:name => %q#【つっ！.COM】 2chまとめにΣ(`・ω・ ´ )#, 
  :url => 'http://tuccom.com', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://tuccom.com/feed',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1829.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1829.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1603)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 8822)
s = Site.create(:name => %q#GOSSIP速報#, 
  :url => 'http://gossip1.net/', 
  :category_id => category_name_binds['芸能'], 
  :feed_url => 'http://gossip1.net/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2050.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2050.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1599)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 11346)
s = Site.create(:name => %q#本当にやった復讐　まとめ#, 
  :url => 'http://revenge.doorblog.jp/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://revenge.doorblog.jp/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1330.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1330.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1594)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 2653)
s = Site.create(:name => %q#台湾の反応 kaola.jp#, 
  :url => 'http://kaola.jp', 
  :category_id => category_name_binds['翻訳'], 
  :feed_url => 'http://kaola.jp/feed/',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1524.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1524.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1577)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 7152)
s = Site.create(:name => %q#watch＠２ちゃんねる#, 
  :url => 'http://www.watch2chan.com', 
  :category_id => category_name_binds['NEWS'], 
  :feed_url => 'http://www.watch2chan.com/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1863.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1863.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1575)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 3993)
s = Site.create(:name => %q#PCパーツまとめ#, 
  :url => 'http://blog.livedoor.jp/bluejay01-review/', 
  :category_id => category_name_binds['その他'], 
  :feed_url => 'http://blog.livedoor.jp/bluejay01-review/index.rdf',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/1219.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/1219.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1562)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 3037)
s = Site.create(:name => %q#でぃあんどる#, 
  :url => 'http://drdinl.com', 
  :category_id => category_name_binds['VIP'], 
  :feed_url => 'http://drdinl.com/feed/',
  :thumbnail_url => 'http://sub.moudamepo.com/screenshot/2077.jpg',
  :icon_url => 'http://sub.moudamepo.com/favicon/2077.png')
DailyInCount.create(:count_date => 20190106, :site_id => s.id, :count => 1514)
DailyOutCount.create(:count_date => 20190106, :site_id => s.id, :count => 21700)
